on: [pull_request]

name: Basic

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: [1.78.0]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust-version }}
          target: wasm32-unknown-unknown
          override: true
      - name: Run unit tests
        run: make test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: [1.78.0]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust-version }}
          override: true
          target: wasm32-unknown-unknown
          components: rustfmt, clippy

      - name: Run cargo clippy
        run: make lints

